### ISSUE TITLE
docker-compose报错

### ISSUE THREAD

**Issue by Howie59** [ccfos/nightingale#1092]
### Relevant server.conf | webapi.conf

```toml
默认配置
```

### Relevant logs

```text
mysql       | 2022-08-08T06:38:07.977232Z 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
mysql       | 2022-08-08T06:38:07.978718Z 0 [Note] InnoDB: 96 redo rollback segment(s) found. 96 redo rollback segment(s) are active.
mysql       | 2022-08-08T06:38:07.978748Z 0 [Note] InnoDB: 32 non-redo rollback segment(s) are active.
mysql       | 2022-08-08T06:38:07.979657Z 0 [Note] InnoDB: Waiting for purge to start
mysql       | 2022-08-08T06:38:08.029988Z 0 [Note] InnoDB: 5.7.39 started; log sequence number 1306730
mysql       | 2022-08-08T06:38:08.030267Z 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
mysql       | 2022-08-08T06:38:08.030607Z 0 [Note] Plugin 'FEDERATED' is disabled.
mysql       | 2022-08-08T06:38:08.031816Z 0 [Note] InnoDB: Buffer pool(s) load completed at 220808 14:38:08
mysql       | 2022-08-08T06:38:08.038462Z 0 [Note] Found ca.pem, server-cert.pem and server-key.pem in data directory. Trying to enable SSL support using them.
mysql       | 2022-08-08T06:38:08.038493Z 0 [Note] Skipping generation of SSL certificates as certificate files are present in data directory.
mysql       | 2022-08-08T06:38:08.038501Z 0 [Warning] A deprecated TLS version TLSv1 is enabled. Please use TLSv1.2 or higher.
mysql       | 2022-08-08T06:38:08.038506Z 0 [Warning] A deprecated TLS version TLSv1.1 is enabled. Please use TLSv1.2 or higher.
mysql       | 2022-08-08T06:38:08.039255Z 0 [Warning] CA certificate ca.pem is self signed.
mysql       | 2022-08-08T06:38:08.039330Z 0 [Note] Skipping generation of RSA key pair as key files are present in data directory.
mysql       | 2022-08-08T06:38:08.039884Z 0 [Note] Server hostname (bind-address): '0.0.0.0'; port: 3306
mysql       | 2022-08-08T06:38:08.039931Z 0 [Note]   - '0.0.0.0' resolves to '0.0.0.0';
mysql       | 2022-08-08T06:38:08.039971Z 0 [Note] Server socket created on IP: '0.0.0.0'.
mysql       | 2022-08-08T06:38:08.133196Z 0 [Warning] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
mysql       | 2022-08-08T06:38:08.134900Z 0 [ERROR] Missing system table mysql.proxies_priv; please run mysql_upgrade to create it
mysql       | 2022-08-08T06:38:08.140722Z 0 [ERROR] Native table 'performance_schema'.'events_statements_summary_global_by_event_name' has the wrong structure
mysql       | 2022-08-08T06:38:08.140793Z 0 [ERROR] Native table 'performance_schema'.'events_statements_summary_by_digest' has the wrong structure
mysql       | 2022-08-08T06:38:08.140835Z 0 [ERROR] Native table 'performance_schema'.'events_statements_summary_by_program' has the wrong structure
mysql       | 2022-08-08T06:38:08.140896Z 0 [ERROR] Native table 'performance_schema'.'events_transactions_current' has the wrong structure
mysql       | 2022-08-08T06:38:08.140941Z 0 [ERROR] Native table 'performance_schema'.'events_transactions_history' has the wrong structure
mysql       | 2022-08-08T06:38:08.140985Z 0 [ERROR] Native table 'performance_schema'.'events_transactions_history_long' has the wrong structure
mysql       | 2022-08-08T06:38:08.141026Z 0 [ERROR] Native table 'performance_schema'.'events_transactions_summary_by_thread_by_event_name' has the wrong structure
mysql       | 2022-08-08T06:38:08.141066Z 0 [ERROR] Native table 'performance_schema'.'events_transactions_summary_by_account_by_event_name' has the wrong structure
mysql       | 2022-08-08T06:38:08.141107Z 0 [ERROR] Native table 'performance_schema'.'events_transactions_summary_by_user_by_event_name' has the wrong structure
mysql       | 2022-08-08T06:38:08.141155Z 0 [ERROR] Native table 'performance_schema'.'events_transactions_summary_by_host_by_event_name' has the wrong structure
mysql       | 2022-08-08T06:38:08.141194Z 0 [ERROR] Native table 'performance_schema'.'events_transactions_summary_global_by_event_name' has the wrong structure
mysql       | 2022-08-08T06:38:08.141226Z 0 [ERROR] Native table 'performance_schema'.'users' has the wrong structure
mysql       | 2022-08-08T06:38:08.141260Z 0 [ERROR] Native table 'performance_schema'.'accounts' has the wrong structure
mysql       | 2022-08-08T06:38:08.141301Z 0 [ERROR] Native table 'performance_schema'.'hosts' has the wrong structure
mysql       | 2022-08-08T06:38:08.141647Z 0 [ERROR] Native table 'performance_schema'.'session_connect_attrs' has the wrong structure
mysql       | 2022-08-08T06:38:08.141699Z 0 [ERROR] Native table 'performance_schema'.'session_account_connect_attrs' has the wrong structure
mysql       | 2022-08-08T06:38:08.141736Z 0 [ERROR] Native table 'performance_schema'.'memory_summary_global_by_event_name' has the wrong structure
mysql       | 2022-08-08T06:38:08.141777Z 0 [ERROR] Native table 'performance_schema'.'memory_summary_by_account_by_event_name' has the wrong structure
mysql       | 2022-08-08T06:38:08.141812Z 0 [ERROR] Native table 'performance_schema'.'memory_summary_by_host_by_event_name' has the wrong structure
mysql       | 2022-08-08T06:38:08.141849Z 0 [ERROR] Native table 'performance_schema'.'memory_summary_by_thread_by_event_name' has the wrong structure
mysql       | 2022-08-08T06:38:08.141906Z 0 [ERROR] Native table 'performance_schema'.'memory_summary_by_user_by_event_name' has the wrong structure
mysql       | 2022-08-08T06:38:08.141957Z 0 [ERROR] Native table 'performance_schema'.'table_handles' has the wrong structure
mysql       | 2022-08-08T06:38:08.141993Z 0 [ERROR] Native table 'performance_schema'.'metadata_locks' has the wrong structure
mysql       | 2022-08-08T06:38:08.142035Z 0 [ERROR] Native table 'performance_schema'.'replication_connection_configuration' has the wrong structure
mysql       | 2022-08-08T06:38:08.142071Z 0 [ERROR] Native table 'performance_schema'.'replication_group_members' has the wrong structure
mysql       | 2022-08-08T06:38:08.142107Z 0 [ERROR] Native table 'performance_schema'.'replication_connection_status' has the wrong structure
mysql       | 2022-08-08T06:38:08.142142Z 0 [ERROR] Native table 'performance_schema'.'replication_applier_configuration' has the wrong structure
mysql       | 2022-08-08T06:38:08.142177Z 0 [ERROR] Native table 'performance_schema'.'replication_applier_status' has the wrong structure
mysql       | 2022-08-08T06:38:08.142221Z 0 [ERROR] Native table 'performance_schema'.'replication_applier_status_by_coordinator' has the wrong structure
mysql       | 2022-08-08T06:38:08.142263Z 0 [ERROR] Native table 'performance_schema'.'replication_applier_status_by_worker' has the wrong structure
mysql       | 2022-08-08T06:38:08.142303Z 0 [ERROR] Native table 'performance_schema'.'replication_group_member_stats' has the wrong structure
mysql       | 2022-08-08T06:38:08.142346Z 0 [ERROR] Native table 'performance_schema'.'prepared_statements_instances' has the wrong structure
mysql       | 2022-08-08T06:38:08.142398Z 0 [ERROR] Native table 'performance_schema'.'user_variables_by_thread' has the wrong structure
mysql       | 2022-08-08T06:38:08.142440Z 0 [ERROR] Native table 'performance_schema'.'status_by_account' has the wrong structure
mysql       | 2022-08-08T06:38:08.142479Z 0 [ERROR] Native table 'performance_schema'.'status_by_host' has the wrong structure
mysql       | 2022-08-08T06:38:08.142519Z 0 [ERROR] Native table 'performance_schema'.'status_by_thread' has the wrong structure
mysql       | 2022-08-08T06:38:08.142558Z 0 [ERROR] Native table 'performance_schema'.'status_by_user' has the wrong structure
mysql       | 2022-08-08T06:38:08.142595Z 0 [ERROR] Native table 'performance_schema'.'global_status' has the wrong structure
mysql       | 2022-08-08T06:38:08.142635Z 0 [ERROR] Native table 'performance_schema'.'session_status' has the wrong structure
mysql       | 2022-08-08T06:38:08.142674Z 0 [ERROR] Native table 'performance_schema'.'variables_by_thread' has the wrong structure
mysql       | 2022-08-08T06:38:08.142711Z 0 [ERROR] Native table 'performance_schema'.'global_variables' has the wrong structure
mysql       | 2022-08-08T06:38:08.142743Z 0 [ERROR] Native table 'performance_schema'.'session_variables' has the wrong structure
mysql       | 2022-08-08T06:38:08.143296Z 0 [Note] Event Scheduler: Loaded 0 events
mysql       | 2022-08-08T06:38:08.143672Z 0 [Note] mysqld: ready for connections.
mysql       | Version: '5.7.39'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server (GPL)
ibex        | [INFO  wait] Host [mysql:3306] is now available!
ibex        | [INFO  wait] --------------------------------------------------------
ibex        | [INFO  wait] docker-compose-wait - Everything's fine, the application can now start!
ibex        | [INFO  wait] --------------------------------------------------------
ibex        | runner.cwd: /app
ibex        | runner.hostname: ibex
ibex        | runner.fd_limits: (soft=1048576, hard=1048576)
ibex        | runner.vm_limits: (soft=unlimited, hard=unlimited)
ibex        | heartbeat.ip: 172.19.0.5
ibex        | heartbeat.interval: 1000ms
ibex        |
ibex        | 2022/08/08 06:38:08 /root/gopath/src/ibex/src/pkg/ormx/ormx.go:45
ibex        | [error] failed to initialize database, got error Error 1130: Host 'ibex.docker_nightingale' is not allowed to connect to this MySQL server
ibex        | server init fail: Error 1130: Host 'ibex.docker_nightingale' is not allowed to connect to this MySQL server
agentd      | runner.cwd: /app
agentd      | runner.hostname: agentd
agentd      | runner.fd_limits: (soft=1048576, hard=1048576)
agentd      | runner.vm_limits: (soft=unlimited, hard=unlimited)
agentd      | host: categraf01
agentd      | http server listening on: 0.0.0.0:2090
nwebapi     | [INFO  wait] --------------------------------------------------------
nwebapi     | [INFO  wait]  docker-compose-wait 2.9.0
nwebapi     | [INFO  wait] ---------------------------
nwebapi     | [DEBUG wait] Starting with configuration:
nwebapi     | [DEBUG wait]  - Hosts to be waiting for: [mysql:3306, redis:6379]
nwebapi     | [DEBUG wait]  - Paths to be waiting for: []
nwebapi     | [DEBUG wait]  - Timeout before failure: 30 seconds
nwebapi     | [DEBUG wait]  - TCP connection timeout before retry: 5 seconds
nwebapi     | [DEBUG wait]  - Sleeping time before checking for hosts/paths availability: 0 seconds
nwebapi     | [DEBUG wait]  - Sleeping time once all hosts/paths are available: 0 seconds
nwebapi     | [DEBUG wait]  - Sleeping time between retries: 1 seconds
nwebapi     | [DEBUG wait] --------------------------------------------------------
nwebapi     | [INFO  wait] Checking availability of host [mysql:3306]
nwebapi     | [INFO  wait] Host [mysql:3306] is now available!
nwebapi     | [INFO  wait] --------------------------------------------------------
nwebapi     | [INFO  wait] Checking availability of host [ redis:6379]
nwebapi     | [INFO  wait] Host [ redis:6379] is now available!
nwebapi     | [INFO  wait] --------------------------------------------------------
nwebapi     | [INFO  wait] docker-compose-wait - Everything's fine, the application can now start!
nwebapi     | [INFO  wait] --------------------------------------------------------
nwebapi     | runner.cwd: /app
nwebapi     | runner.hostname: nwebapi
nwebapi     | runner.fd_limits: (soft=1048576, hard=1048576)
nwebapi     | runner.vm_limits: (soft=unlimited, hard=unlimited)
nwebapi     |
nwebapi     | 2022/08/08 14:38:12 /home/runner/work/nightingale/nightingale/src/pkg/ormx/ormx.go:45
nwebapi     | [error] failed to initialize database, got error Error 1130: Host 'nwebapi.docker_nightingale' is not allowed to connect to this MySQL server
nwebapi     | webapi init fail: Error 1130: Host 'nwebapi.docker_nightingale' is not allowed to connect to this MySQL server
ibex exited with code 1
nserver     | [INFO  wait] --------------------------------------------------------
nserver     | [INFO  wait]  docker-compose-wait 2.9.0
nserver     | [INFO  wait] ---------------------------
nserver     | [DEBUG wait] Starting with configuration:
nserver     | [DEBUG wait]  - Hosts to be waiting for: [mysql:3306, redis:6379]
nserver     | [DEBUG wait]  - Paths to be waiting for: []
nserver     | [DEBUG wait]  - Timeout before failure: 30 seconds
nserver     | [DEBUG wait]  - TCP connection timeout before retry: 5 seconds
nserver     | [DEBUG wait]  - Sleeping time before checking for hosts/paths availability: 0 seconds
nserver     | [DEBUG wait]  - Sleeping time once all hosts/paths are available: 0 seconds
nserver     | [DEBUG wait]  - Sleeping time between retries: 1 seconds
nserver     | [DEBUG wait] --------------------------------------------------------
nserver     | [INFO  wait] Checking availability of host [mysql:3306]
nserver     | [INFO  wait] Host [mysql:3306] is now available!
nserver     | [INFO  wait] --------------------------------------------------------
nserver     | [INFO  wait] Checking availability of host [ redis:6379]
nserver     | [INFO  wait] Host [ redis:6379] is now available!
nserver     | [INFO  wait] --------------------------------------------------------
nserver     | [INFO  wait] docker-compose-wait - Everything's fine, the application can now start!
nserver     | [INFO  wait] --------------------------------------------------------
nserver     | runner.cwd: /app
nserver     | runner.hostname: nserver
nserver     | runner.fd_limits: (soft=1048576, hard=1048576)
nserver     | runner.vm_limits: (soft=unlimited, hard=unlimited)
nserver     | heartbeat.ip: nserver+8
nserver     | heartbeat.interval: 1000ms
nserver     |
nserver     | 2022/08/08 14:38:13 /home/runner/work/nightingale/nightingale/src/pkg/ormx/ormx.go:45
nserver     | [error] failed to initialize database, got error Error 1130: Host 'nserver.docker_nightingale' is not allowed to connect to this MySQL server
nserver     | server init fail: Error 1130: Host 'nserver.docker_nightingale' is not allowed to connect to this MySQL server
categraf    | /entrypoint.sh: 5: setcap: not found
categraf    | Failed to set additional capabilities on /usr/bin/categraf
agentd      | 2022/08/08 06:38:18 cli.go:41: W: dial ibex:20090 fail: dial tcp: i/o timeout
agentd      | 2022/08/08 06:38:18 cli.go:75: E: no job server found
categraf    | 2022/08/08 06:38:18 main.go:113: I! runner.binarydir: /usr/bin
categraf    | 2022/08/08 06:38:18 main.go:114: I! runner.hostname: categraf01
categraf    | 2022/08/08 06:38:18 main.go:115: I! runner.fd_limits: (soft=1048576, hard=1048576)
categraf    | 2022/08/08 06:38:18 main.go:116: I! runner.vm_limits: (soft=unlimited, hard=unlimited)
categraf    | 2022/08/08 06:38:18 config.go:33: I! tracing disabled
categraf    | 2022/08/08 06:38:18 agent.go:65: I! agent starting
categraf    | panic: runtime error: invalid memory address or nil pointer dereference
categraf    | [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2e587f4]
categraf    |
categraf    | goroutine 100 [running]:
categraf    | flashcat.cloud/categraf/api.Start()
categraf    |   /home/runner/work/categraf/categraf/api/server.go:17 +0x34
categraf    | created by main.main
categraf    |   /home/runner/work/categraf/categraf/main.go:70 +0x171

```
```


### System info

n9e-latest

### Steps to reproduce

1.docker-compose部署

### Expected behavior

部署成功

### Actual behavior

mysql报错，agent，webapi没起来

### Additional info

_No response_

**Comment by kongfei605** [comment]
failed to initialize database, got error Error 1130: Host 'nwebapi.docker_nightingale' is not allowed to connect to this MySQL server
环境清理干净重新启动下

**Comment by Howie59** [comment]
> failed to initialize database, got error Error 1130: Host 'nwebapi.docker_nightingale' is not allowed to connect to this MySQL server 环境清理干净重新启动下

怎么清理哦
