### ISSUE TITLE
bug: panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by lizeyun** [ccfos/nightingale#1461]
版本： v6.0.0-ga2

报错提示：
```shell
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x911d74]

goroutine 167 [running]:
html/template.(*Template).escape(0x0)
        /opt/hostedtoolcache/go/1.18.10/x64/src/html/template/template.go:97 +0x34
html/template.(*Template).Execute(0x0, {0x1412fc0, 0xc0006b9c20}, {0x11c9c20, 0xc000220280})
        /opt/hostedtoolcache/go/1.18.10/x64/src/html/template/template.go:121 +0x32
github.com/ccfos/nightingale/v6/alert/process.(*Processor).fillTags(0xc000662180, {{0xc00134a2d0, 0x22}, 0xc0006b9770, 0x6429503a, 0xc00db3656aa24cfc, 0x3, 0x0})
        /home/runner/work/nightingale/nightingale/alert/process/process.go:384 +0x4bb
github.com/ccfos/nightingale/v6/alert/process.(*Processor).BuildEvent(0xc000662180, {{0xc00134a2d0, 0x22}, 0xc0006b9770, 0x6429503a, 0xc00db3656aa24cfc, 0x3, 0x0}, {0x1254aea, 0x5}, ...)
        /home/runner/work/nightingale/nightingale/alert/process/process.go:149 +0x9f
github.com/ccfos/nightingale/v6/alert/process.(*Processor).Handle(0xc000662180, {0xc001195380?, 0x1, 0x1}, {0x1254aea, 0x5}, 0xc0?)
        /home/runner/work/nightingale/nightingale/alert/process/process.go:129 +0x3c6
github.com/ccfos/nightingale/v6/alert/eval.(*AlertRuleWorker).Eval(0xc000d3af80)
        /home/runner/work/nightingale/nightingale/alert/eval/eval.go:108 +0xfc
github.com/ccfos/nightingale/v6/alert/eval.(*AlertRuleWorker).Start.func1()
        /home/runner/work/nightingale/nightingale/alert/eval/eval.go:78 +0x32
created by github.com/ccfos/nightingale/v6/alert/eval.(*AlertRuleWorker).Start
        /home/runner/work/nightingale/nightingale/alert/eval/eval.go:72 +0x155
```

碰到好几次了，程序直接奔溃了。

**Comment by 710leo** [comment]
我们看下

**Comment by 710leo** [comment]
fix in https://github.com/ccfos/nightingale/commit/1ce79e29d5652c32ab35dd12a395e1ca75b5a9d4
