### ISSUE TITLE
Update 最新代码后 触发的 Panic 错误

### ISSUE THREAD

**Issue by jicki** [ccfos/nightingale#1629]
### Relevant server.conf | webapi.conf

```toml
none
```

### Relevant logs

```text
panic: strings: negative Repeat count

goroutine 1 [running]:
strings.Repeat({0x2386f81?, 0x0?}, 0x0?)
        /usr/local/go/src/strings/strings.go:533 +0x4d8
nightingale/v6/memsto.(*NotifyConfigCacheType).syncNotifyConfigs(0xc00039e4b0)
        /nightingale/memsto/notify_config.go:113 +0xa2c
nightingale/v6/memsto.(*NotifyConfigCacheType).SyncNotifyConfigs(0xc00039e4b0)
        /nightingale/memsto/notify_config.go:53 +0x25
nightingale/v6/memsto.NewNotifyConfigCache(...)
        /nightingale/memsto/notify_config.go:48
nightingale/v6/center.Initialize({0x134d1a9, 0x3}, {0x0?, 0x0?})
        /nightingale/center/center.go:75 +0x845
main.main()
        /nightingale/cmd/center/main.go:34 +0xfa

```
```


### System info

v6-ga14

### Steps to reproduce

none

### Expected behavior

none

### Actual behavior

none

### Additional info

_No response_

**Comment by jicki** [comment]
@UlricQin

**Comment by UlricQin** [comment]
修了
