### ISSUE TITLE
v6.7.3添加图表时输入时间会导致白屏

### ISSUE THREAD

**Issue by Aklscc** [ccfos/nightingale#1967]
### Your config.toml

```toml
无关
```

### Relevant logs

```text
TypeError: Cannot read properties of undefined (reading 'toString')
    at nce (index.24deb0e2.js:61:95252)
    at index.24deb0e2.js:61:99242
    at $t (vendor.55e08823.js:116:8194)
    at Function.D0 [as map] (vendor.55e08823.js:118:10169)
    at B4e (index.24deb0e2.js:61:99070)
    at T8 (vendor.55e08823.js:30:53042)
    at PP (vendor.55e08823.js:34:8819)
    at CP (vendor.55e08823.js:34:951)
    at Qj (vendor.55e08823.js:34:879)
    at hh (vendor.55e08823.js:34:732)
```

### System info

n9e v6.7.3

### Steps to reproduce

1. 打开监控仪表盘
2. 添加一个图表
3. 选择时序图
4. 点开 Legend 后面的 【时间选择】
5. 在开始时间栏输入 `now-12h`, 提示时间格式错误。之后，会无限进入白屏
6. 只要涉及图表相关的，均会白屏

...

### Expected behavior

正常运行

### Actual behavior

正常运行

### Additional info

版本 v.6.7.3

**Comment by 710leo** [comment]
最新版本没有复现你这个问题，可以升级到最新的版本
